@baseUrl=http://localhost:4200/api
@resourceName=categories

# @name getAll
GET {{baseUrl}}/categories

###

# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
    "name": "Laptop"
}

###
# @name update
PATCH  {{baseUrl}}/{{resourceName}}/2
Content-Type: application/json

{
    "name": "New Laptop"
}

###
# @name remove
DELETE {{baseUrl}}/{{resourceName}}/2