@baseUrl=http://localhost:4200/api
@resourceName=products

# @name getAll
GET {{baseUrl}}/{{resourceName}}

###

# @name getAll
GET {{baseUrl}}/{{resourceName}}?_sort=createAt&_order=desc&_limit=4

###

# @name filter
GET {{baseUrl}}/{{resourceName}}?name=Laptop&price_gte=200

###

# @name filter
GET {{baseUrl}}/{{resourceName}}?id_ne=474a1532-dd6a-42d9-afcf-a04817ae02dh&&categoryId=26b4e7fb-8a62-4b59-8489-ab5609141242

###

# @name filter
GET {{baseUrl}}/{{resourceName}}?name_like=Steel 

###

# @name pagination
GET {{baseUrl}}/{{resourceName}}?_page=2&_limit=5

###

# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=desc

###

# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
    "name": "Laptop",
    "price": "131.00",
    "description": "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
    "thumnailUrl": "http://placeimg.com/400/400"
}

###
# @name update
PATCH  {{baseUrl}}/{{resourceName}}/nj5_G2j
Content-Type: application/json

{
    "name": "Laptop 234",
    "price": "131.00",
    "description": "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
    "thumnailUrl": "http://placeimg.com/400/400"
}

###
# @name remove
DELETE {{baseUrl}}/{{resourceName}}/G2CDawP